language: python
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=flake8
# Disable coverage until coveralls is fixed. See https://github.com/lemurheavy/coveralls-public/issues/522.  
#  - TOX_ENV=cover
  - TOX_ENV=language_de
  - TOX_ENV=language_el
  - TOX_ENV=language_es
  - TOX_ENV=language_fr
  - TOX_ENV=language_it
  - TOX_ENV=language_nl
  - TOX_ENV=language_pt_BR
install:
  - pip install tox
script: tox -e $TOX_ENV
